### ISSUE TITLE
Can this plugin be used from the library level

### ISSUE THREAD

**Issue by jd-alexander** [Archinamon/GradleAspectJ-Android#1]
I want to use Aspect J in library. I tried using  uPhyca's plugin but when I referenced the library from my app project it doesn't work. Does this support it?

**Comment by Archinamon** [comment]
In case my and uPhyca's plugin operates over compile tasks, you have to use it on the top-level of your app. If you use it on lib level only, so your main app won't be able to use aspects.
Build tasks under library module won't affect the compile tasks scope of any other modules.

**Comment by jd-alexander** [comment]
Alright thanks.
