### ISSUE TITLE
Can provide simple case? First contact with this Lib, do't know how to use it.

### ISSUE THREAD

**Issue by RonnyWu** [Archinamon/GradleAspectJ-Android#10]
Hey! Archinamon. I just started learning based on AOP Android development, do not know can not be provided based on a simple case of the lib. I according to the home page shows the correct configuration of the Gradle, but it was not clear if the Lib of AOP development.Can you help me?

**Comment by Archinamon** [comment]
Hi, Ronny!
Clarify please your use case. Do you want to use AOP to build android-library, or simple android application project? In the second case you may look on my example project: https://github.com/Archinamon/AspectJExampleAndroid

Maybe I should add it as reference in readme for a plugin. :)
