### ISSUE TITLE
AspectJ version?

### ISSUE THREAD

**Issue by renaudcerrato** [Archinamon/GradleAspectJ-Android#13]
Can't you add a way to change the AspectJ version?

**Comment by Archinamon** [comment]
No way. AJ-version constantly defines on plugin compile step.

**Comment by Archinamon** [comment]
I've got couple minds about to achieve this option w/o defining extra classpath in work-project, simply using aspectj-extension options. Will look for this job soon. Thank's for an issue!

**Comment by renaudcerrato** [comment]
Great! For now, I ended up copying your groovy files into my buildscript
folder. Will wait for a fix then! Thanks for that plugin, he's the only one
working flawlessly on our gigantic project!

**Comment by Archinamon** [comment]
Implemented in 1.3.3;

**Comment by renaudcerrato** [comment]
Amazing!

**Comment by Archinamon** [comment]
You may use parameter:
aspectj {
    ajc "1.8.9"
}
Added this to a readme description too :)
