### ISSUE TITLE
Transform API?

### ISSUE THREAD

**Issue by renaudcerrato** [Archinamon/GradleAspectJ-Android#15]
Since your plugin is the most solid out there, I was just wondering if you looked at the [Transform API](http://tools.android.com/tech-docs/new-build-system/transform-api) and had plans to move to it? 

https://afterecho.uk/blog/create-a-standalone-gradle-plugin-for-android-part-4-the-transform-api.html

**Comment by Archinamon** [comment]
I'm not sure I'll have enough time to refactor existing codebase on Transform API. Maybe in few month later I'll move on this point :)

**Comment by Archinamon** [comment]
Released 2.0.1 with Transform API mechanics.

**Comment by renaudcerrato** [comment]
Wow!! That was fast!!! Congratulations on that
