### ISSUE TITLE
Tests source sets

### ISSUE THREAD

**Issue by renaudcerrato** [Archinamon/GradleAspectJ-Android#16]
I wrote a small android library based on AspectJ, along with some unit tests but running `./gradlew library:check` simply fails because none of my tests have been weaved: I can clearly see the AJC compiler running twice (on `sourceSets.main`, then on `sourceSets.test`).

On a previous Java projects, I had the same problem on [that plugin](https://github.com/eveoh/gradle-aspectj), and it was easily solved by declaring:  `testAspectpath sourceSets.main.output` to my dependencies.

Your plugin is missing a way to instruct him to include the main source sets.

**Comment by Archinamon** [comment]
I have strong plans to re-write all base on Transform API. This issue should be fixed by this migration :)

**Comment by renaudcerrato** [comment]
Glad to read that! Please keep me updated, as I'm heavily relying on your plugin!

**Comment by Archinamon** [comment]
Should be fixed with new release on Transform API.
