### ISSUE TITLE
Make /src/main/aspectj non obligatory

### ISSUE THREAD

**Issue by mikekudzin** [Archinamon/GradleAspectJ-Android#23]
Comrades, it there any reason of making this sources folder("/src/main/aspectj") mandatory?
Ajc throws an error during build process: "[error] build config error: bad sourceroot: C;\git\Project\src\main\aspectj"

Use case describing this issue.
I am going to precompile and distribute some aspects in binary form within an .aar package. Main idea: a developer can utilize functionality provided by aspects from .aar library in his app by adding GradleAspectJ plugin to their build.

I can provide fix for this but just want to be sure it won't contradict anything.
Regards.
//cc @Archinamon

**Comment by Archinamon** [comment]
Existence of sourceroot shouldn't be obligatory but aj files should be stored only within src/*/aspectj folders.
