### ISSUE TITLE
Experiencing troubles with includeAspectsFromJar

### ISSUE THREAD

**Issue by mikekudzin** [Archinamon/GradleAspectJ-Android#26]
Looks like this cleanup commit broke proper plugin execution 
https://github.com/Archinamon/GradleAspectJ-Android/commit/55bbece0468ce7ec4b8e628a0804948ead4ff627

I have performed debugging around def isFilterMatched(String str, List<String> filters, FilterPolicy filterPolicy) execution. Appears it returns false even if within
`for (String s : filters) {
              if (isContained(str, s)) {
                 true;
              }
          }`
isContained returns true. Possibly because of enclosing for loop. [Here ](http://stackoverflow.com/a/12926006/1562477)is a discussion on the same problem.

**Comment by Archinamon** [comment]
Wow. That's new. I'll re-upload 2.2.0 artifacts and will fix it separately on 2.2.1 to handle existing users.

**Comment by Archinamon** [comment]
Try with new artifacts or re-upload 2.2.0 please.
