### ISSUE TITLE
thoughts on other similar libraries....

### ISSUE THREAD

**Issue by sirvon** [Archinamon/GradleAspectJ-Android#3]
Thanks for your work...

There are similar plugins out there in the wild...

Just wanted your thoughts on the similarites, disadvatages, etc btw them all.

https://github.com/eveoh/gradle-aspectj
https://github.com/leolin310148/GradleAndroidAspectJPlugin
https://github.com/Archinamon/GradleAspectJ-Android

Thank You.

*I've raised the same issue with the other library authors.

**Comment by Archinamon** [comment]
Hi! Thanks for your remark.

I can say nothing bad about all these plugins. They've gave me expirience allowed to write my own implementation.
About leoli's plugin can mention that his impl doesn't support native aspectj's syntax. Other plugins I saw doesn't supports or Retrolambda, AndroidAnnotations, other exotic plugins for Java within android studio, or product flavors, native syntax, etc.

**Comment by normanhh3** [comment]
I've tried gradle-aspectj and the original implementation that this one is forked from and both fell down when trying to do things like AspectJ + AndroidAnnotations and my next move is to get Retrolambda working as well!

Thanks so much for your efforts @Archinamon!

**Comment by Archinamon** [comment]
@normanhh3 can you, please, describe what went wrong with my plugin when you tried to run it with AndroidAnnotations? :)

**Comment by normanhh3** [comment]
Nothing wrong with your version. :-). That was the one that helped me get
everything working.
