### ISSUE TITLE
after produce apk，aspectj can not work

### ISSUE THREAD

**Issue by zhoujunqz** [Archinamon/GradleAspectJ-Android#30]
In android sutdio,I use assembleRelease prodce apk,but aspectj can not work!!!  
why?

**Comment by Archinamon** [comment]
Can you provide more info about the issue you've faced? Any logs and details will be great.

**Comment by zhoujunqz** [comment]
@Archinamon 
it is very strange！In android studio,i run app.It is running normally（Log is printed）.
But I use "assembleRelease" to produce apk,then,install to phone.Aspectj can not work(Log is not printed)!!!

it is my code

@Aspect
public class DemoAspect {
@Pointcut("execution(* *..MainActivity.guaxiaoxi(..))")
public void gua() {
}
@Before("gua()")
public void guaxiao(JoinPoint joinPoint) {
Log.e("TAG","success");
}
}

public class MainActivity extends Activity {
@Override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
setContentView(R.layout.activity_main);
guaxiaoxi();
}

public void guaxiaoxi(){}
}

**Comment by mikekudzin** [comment]
@zhoujunqz
Do you have minifyEnabled true in your project's build.gradle?

**Comment by Archinamon** [comment]
@zhoujunqz please, look at app/build/ajc-details.log file and copy the content here in comment.

**Comment by zhoujunqz** [comment]
@mikekudzin  @Archinamon thank you.I solve the problem。 I am so stupid! There is something wrong with build.gradle obviously.
