### ISSUE TITLE
handle aspectj syntax in Android Studio: 404 file not found (aspect.zip)

### ISSUE THREAD

**Issue by ardmn** [Archinamon/GradleAspectJ-Android#31]
Can't download file [aspect.zip](https://github.com/Archinamon/GradleAspectJ-Android/blob/master/IDE/aspect.zip)

**Comment by Archinamon** [comment]
you've missed a char 'j' before .zip
It's available for download.

**Comment by ardmn** [comment]
You too :) on this [page](https://github.com/Archinamon/GradleAspectJ-Android/tree/master/IDE)

**Comment by Archinamon** [comment]
sure.. your truth, will fix it, thanks!
