### ISSUE TITLE
 Execution failed for task ':app:transformClassesWithAspectjForDebug'

### ISSUE THREAD

**Issue by FunnyDevs** [Archinamon/GradleAspectJ-Android#36]
Hi! I have this message when i try to run the app and  there isn't ajc-details.log to read the log problem.

**Comment by Archinamon** [comment]
Hi! Try to recompile with --info flag and look for some more info, please :)

**Comment by Archinamon** [comment]
Try out the latest version, please. Until any news incomes I'm closing this issue.

**Comment by FunnyDevs** [comment]
Thanks, now it works and there is no problem!
