### ISSUE TITLE
Migrate to Kotlin instead of Groovy

### ISSUE THREAD

**Issue by Archinamon** [Archinamon/GradleAspectJ-Android#37]
In groovy it's hard to work with dynamic contexts and Android Studio supports groovy wierd, so it's better to re-write plugin in Kotlin to make easier further development.

**Comment by Archinamon** [comment]
3.0.0 artifacts are available within:
`maven { url "https://raw.github.com/Archinamon/GradleAspectJ-Android/kotlin-beta" }` as repositories url
`classpath 'com.archinamon:android-gradle-aspectj:3.0.0'`

Then as usually `apply plugin: 'com.archinamon.aspectj'` or `apply plugin: 'com.archinamon.aspectj-ext'` for extended mode.

**Comment by Archinamon** [comment]
@saulmm @renaudcerrato
Guys you're the most active and partial users so I'd wanna ask you to try out 3.0.0 beta from `tree/kotlin-beta` branch and feedback here :) The artifacts available only from `maven { url "https://raw.github.com/Archinamon/GradleAspectJ-Android/kotlin-beta" }` for now. Will appreciate your help a lot!

**Comment by saulmm** [comment]
My pleasure!, will give you feedback asap 👍

**Comment by renaudcerrato** [comment]
Thanks!

**Comment by Archinamon** [comment]
Seems everything works fine in Kotlin? :) So I'll merge it today and update Example project.
