### ISSUE TITLE
Can this be used outside of Android projects?

### ISSUE THREAD

**Issue by GuyPaddock** [Archinamon/GradleAspectJ-Android#39]
This looks like the only complete AspectJ plug-in for Gradle that supports compiling *.aj separately from Java. I was wondering if there is any problem or drawback to using this project outside of an Android Gradle project (for example, Spring).

**Comment by Archinamon** [comment]
Nowdays the plugin depends on android's compile flow and Transform API. I'm planning to write a java/groovy/kotlin/scala separate implementation in future. So stay tuned or contribute :)

In general, needs to unbound compiler task from android structure and write a weaver-task on pure gradle mechanics. Also I have a little expirience with pure java projects so dunno about some specific stuff that could broke this idea.

**Comment by Archinamon** [comment]
No time to write a pure java wrapper :(
