### ISSUE TITLE
Simple mode lacks JarMerging

### ISSUE THREAD

**Issue by Badya** [Archinamon/GradleAspectJ-Android#44]
**Preconditions:**
I have classpath dependecy added sa written in instruction.
I use android library (`my-library.aar`) containing aspects for androidTest, and basically have no aspects in app itself.
I have applied `apply plugin: 'com.archinamon.aspectj'` and configured `includeAspectsFromJar 'my-library'` in `aspectj` section.
In `ajc-transform.log` i see an info that weaving was OK, and join points advised.

**Problem:**
When i launch Instrumentation tests my app fails to start due to:
```stacktrace
 java.lang.ClassNotFoundException: Didn't find class "com.example.MyApp" on path: DexPathList ...
```

**Workaround:**
If we switch plugin to complex mode everything works like a charm:
```groovy
apply plugin: 'com.archinamon.aspectj-ext'
```

**Solution:**
Remove `modeComplex()` check from _com.archinamon.api.AspectJTransform#transform(com.android.build.api.transform.TransformInvocation)_
```kotlin
            // if (modeComplex()) {
            aspectJMerger.doMerge(this, transformInvocation, outputDir)
            // }
```

**Comment by Archinamon** [comment]
Removing this check you'll brake working in main module with InstantRun and will get a ZipException when instantRun slicer tries to merge all sources into single dex.

**Comment by Badya** [comment]
@Archinamon, as far as i concerned there are some issues about InstantRun and multidex support, so we can return this check, but need an update in README.md that using multidex requires complex mode - am i right?

**Comment by Archinamon** [comment]
Seems so. Other way good point is to make a `aspectj-test` plugin with a different configs. That look much more flexible in future :) This way we strictly define usage in tests mostly (without instantrun or some other features).

**Comment by Badya** [comment]
commited with #42 in message =(

**Comment by Badya** [comment]
@Archinamon, I think we can close this issue.
