### ISSUE TITLE
README.md and published version inconsistency

### ISSUE THREAD

**Issue by mikekudzin** [Archinamon/GradleAspectJ-Android#48]
Hi!
[README.md](https://github.com/Archinamon/GradleAspectJ-Android/commit/9e1da26652f77db39b5219c3716c2a1037ba4c12#diff-04c6e90faac2675aa89e2176d2eec7d8R9)  declares the latest  version of the plugin is 3.0.2, however [jitpack](https://jitpack.io/#Archinamon/GradleAspectJ-Android) says 3.0.0 is the latest.

Does it a mistake or a result of a publish delay?

Regards.

**Comment by Archinamon** [comment]
Hi! it's now an error, I forgot to publish a release

**Comment by Archinamon** [comment]
JitPack is going to build 3.0.2 :) Thank's for feedback!
