### ISSUE TITLE
Error while building using android gradle plugin 2.5.0-alpha-preview-01

### ISSUE THREAD

**Issue by mikekudzin** [Archinamon/GradleAspectJ-Android#49]
Hi!
I have tried to run preemptive compatibility testing with 
* android gradle plugin 2.5.0-alpha-preview-01
* gradle-3.5
* GradlewAspectJ plugin 3.0.2

(More details [here](http://tools.android.com/tech-docs/new-build-system/2-5-alpha-gradle-plugin) and [here](http://tools.android.com/tech-docs/new-build-system/2-5-alpha-gradle-plugin/trying-gradle-plugin-2-5))
And got the error running, for instance,  **gradlew help**:
>A problem occurred configuring project ':Demo'.
>  Failed to notify project evaluation listener.
   > com.android.build.gradle.internal.scope.VariantScope.getInstantRunBuildContext()Lcom/android/build/gradle/internal/incremental/InstantRunBuildContext;

**Comment by Archinamon** [comment]
Code base adapted for gradle plugin 2.3.3; So it's not actual no more. I'm currently working on adapting for 3.0.0 plugin:
`classpath 'com.archinamon:android-gradle-aspectj:3.1.1-gradleApiBeta'`

Sources available in separate branch (temporary): https://github.com/Archinamon/GradleAspectJ-Android/tree/feature/gradleApiBeta_3.0.0-beta7
