### ISSUE TITLE
Build failen in case of a lint error

### ISSUE THREAD

**Issue by Viacheslav01** [Archinamon/GradleAspectJ-Android#52]
The following error stoped a build

"XXX-1.13.jar [error] can't determine implemented interfaces of missing type org.apache.http.client.methods.HttpPost
when weaving type XXX$XXX
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0
 [Xlint:cantFindType]
(no source information available)
	[Xlint:cantFindType]"

It seems like an issue in the AJ compiler which could not find a type from an external lib used in my class.

**Comment by Archinamon** [comment]
May help adding in build.gradle:
```groovy
aspectj {
    ajcArgs << '-Xlint:ignore'
}
```
