### ISSUE TITLE
Compile error with Gradle 4.0

### ISSUE THREAD

**Issue by HaukeRa** [Archinamon/GradleAspectJ-Android#55]
While switching over to Android Studio 3.0, which uses Gradle 4.0 compiling fails with the following setup.

* Android application depends on Java-library module
* Android application has "apply plugin: 'com.archinamon.aspectj'"

As far as I understand Gradle 4.0 does not build .jar files anymore to speed up builds. Instead it works on .class files of dependencies directly.

The com.archinamon.aspectj plugin depends on the jar files, which makes the build (actually already the configuration phase) fail.

Example project: https://github.com/HaukeRa/Archinamon-GradleAspectJ-Android-FailureTestProject

**Comment by Archinamon** [comment]
Thanks for reporting! I'll take a look as soon as I'll have some time.

**Comment by Archinamon** [comment]
Hello again!

Please, try out my adapted code for gradle plugin 3.0.0-beta7:
`classpath 'com.archinamon:android-gradle-aspectj:3.1.1-gradleApiBeta'`

Sources available in separate branch (temporary): https://github.com/Archinamon/GradleAspectJ-Android/tree/feature/gradleApiBeta_3.0.0-beta7
