### ISSUE TITLE
Doesn't work with Android Studio 3.0

### ISSUE THREAD

**Issue by davidwong** [Archinamon/GradleAspectJ-Android#61]
I'm using Android Studio 3.0.0-beta7 and the code has an annotation style aspect in it. 

The app compiled but was not able to run (had a ClassNotFoundException on the application class, even though that class was not involved in the weaving). I'm not sure any weaving occurred anyway.

Had a look at at [issue 55](https://github.com/Archinamon/GradleAspectJ-Android/issues/55) regarding Gradle 4. So I went back to Android Studio 2.3, but with the gradle wrapper updated to Gradle 4.1. That worked fine, so I suspect the problem is actually with the android gradle plugin 3.0.

Please note this was tested with an annotation style aspect, haven't tried with aj file.

**Comment by Archinamon** [comment]
Hi!

Please use gradle plugin 2.3.+ for now. Update to 3.+ is coming soon :)

**Comment by davidwong** [comment]
Thanks, appreciate your work and looking forward to the update.

**Comment by Archinamon** [comment]
Hello again!

Please, try out my adapted code for gradle plugin 3.0.0-beta7:
`classpath 'com.archinamon:android-gradle-aspectj:3.1.1-gradleApiBeta'`

Sources available in separate branch (temporary): https://github.com/Archinamon/GradleAspectJ-Android/tree/feature/gradleApiBeta_3.0.0-beta7
