### ISSUE TITLE
Android Gradle Plugin 3.0.0 and Gradle 4.1 JarMerger Class not Found

### ISSUE THREAD

**Issue by JustinTullgren** [Archinamon/GradleAspectJ-Android#63]
Hi,

`Android Gradle Plugin: 3.0.0`
`Gradle Version: 4.1`
`GradleAspectJ-Android: 3.1.1`

Task that is failing: `transformClassesWithAspectjForDebug`

Error:
```
Caused by: java.lang.ClassNotFoundException: com.android.build.gradle.internal.transforms.JarMerger
```

The android gradle plugin changed and introduced breaking changes, including a different dsl.

Is there a workaround for this issue?  Is Android plugin 3.0.0 on the road map?

Thanks!

**Comment by Archinamon** [comment]
Hi! Thank's for feedback!

Temp workaround: https://github.com/Archinamon/GradleAspectJ-Android/tree/feature/gradleApiBeta_3.0.0-beta7

I'll release new stable for 3.0.0 gradle rc soon :)

**Comment by JustinTullgren** [comment]
Hi,

Thanks for the quick answer and workaround.  

I'll close the ticket.
