### ISSUE TITLE
Breaking change from android-gradle plugin 3.3.0

### ISSUE THREAD

**Issue by sjcqs** [Archinamon/GradleAspectJ-Android#91]
Once again, android gradle update 3.3.0 brings some breaking changes to the library.

## Versions
- android-gradle-aspectj 3.3.0
- android-gradle 3.3.0
- gradle-wrapper: 4.10.1
- android studio 3.3.0

## Error
```Unable to find method ‘com.android.build.gradle.internal.scope.TaskContainer.getJavacTask()Lorg/gradle/api/tasks/compile/JavaCompile;```

I submitted a pull request (#90 ) with a solution. Unfortunately, tests doesn't seem to pass on Travis CI while passing locally.

**Comment by shahdab-aalam-saifi** [comment]
@Archinamon @jdappel do you have any update on this issue?
